# Generated by Django 3.1.1 on 2020-10-11 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_remove_goulmetmodel_opiton'),
    ]

    operations = [
        migrations.AddField(
            model_name='goulmetmodel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
