# Generated by Django 3.1.1 on 2020-10-24 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_app', '0001_initial'),
        ('reservation', '0002_ordermodel_date'),
        ('account', '0004_goulmetmodel_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('goulmet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.goulmetmodel')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.ordermodel')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.schedule')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.IntegerField(verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('goulmet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.goulmetmodel')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.roommodel')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
