# Generated by Django 3.1.1 on 2020-10-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_roommodel_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='メッセージ'),
        ),
    ]
