# Generated by Django 3.1.1 on 2020-10-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButtonModel',
        ),
    ]
