# Generated by Django 3.1.1 on 2020-10-08 07:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20201001_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField(verbose_name='基本料金')),
                ('start_time', models.TimeField(default=datetime.time(7, 0), verbose_name='開始時間')),
                ('end_time', models.TimeField(default=datetime.time(7, 0), verbose_name='終了時間')),
                ('goulmet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goulmet_id', to='account.goulmetmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_price', models.IntegerField(verbose_name='追加料金')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.optionmodel')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.ordermodel')),
            ],
        ),
    ]
