# Generated by Django 3.1.1 on 2020-10-16 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
            preserve_default=False,
        ),
    ]
